updated dependencies for chroot

diff --git a/01_create_debian_multi b/01_create_debian_multi
--- a/01_create_debian_multi
+++ b/01_create_debian_multi
@@ -88,8 +88,18 @@ apt-get -y install software-properties-common
 dpkg --add-architecture i386
 apt-get update
 
+install_libs() {
+    for i in \$@ ; do
+        if ! apt-get install -y "\$i" ; then
+            echo "ERROR while installing: \$i"
+            exit 1
+        fi
+    done
+}
+
 echo "Wine dependencies"
-apt-get install -y gcc-10 gcc-multilib g++-10 g++-multilib \
+install_libs \
+                gcc-10 gcc-multilib g++-10 g++-multilib \
                 g++-mingw-w64-x86-64 g++-mingw-w64-i686 \
                 gcc-mingw-w64-x86-64 gcc-mingw-w64-i686 \
                 git sudo autoconf flex bison perl gettext \
@@ -132,25 +142,23 @@ apt-get install -y gcc-10 gcc-multilib g++-10 g++-multilib \
                 libgcrypt-dev libgpg-error-dev \
                 x11proto-dev \
                 libdrm-dev libdrm-dev:i386 \
-                libxkbcommon-dev libxkbcommon-dev:i386 \
-                || echo "FATAL ERROR"
+                libxkbcommon-dev libxkbcommon-dev:i386
 
-apt-get install -y \
+install_libs \
                 libxcb-xkb-dev libxcb-xkb-dev:i386 \
                 libxcb-xkb1 libxcb-xkb1:i386 \
                 libxcb1-dev libxcb1-dev:i386 \
                 libxml++2.6-dev libxml++2.6-dev:i386 \
                 bash-completion wayland-protocols \
-                valgrind || echo "FATAL ERROR"
-
-                sleep 5
+                valgrind
 
 echo "More wine dependencies"
 sleep 1
-apt-get install -y ccache netbase curl ca-certificates \
-				xserver-xorg-video-dummy xserver-xorg xfonts-base xinit fvwm \
-				winbind fonts-liberation2 fonts-noto-core fonts-noto-cjk pulseaudio \
-                python-setuptools openssl || echo "FATAL ERROR"
+install_libs \
+                ccache netbase curl ca-certificates \
+                xserver-xorg-video-dummy xserver-xorg xfonts-base xinit fvwm \
+                winbind fonts-liberation2 fonts-noto-core fonts-noto-cjk pulseaudio \
+                python-setuptools openssl
 
 # Gstreamer codecs
 
@@ -160,22 +168,37 @@ echo 'deb https://www.deb-multimedia.org bullseye main' >> /etc/apt/sources.list
 rm deb-multimedia-keyring_2016.8.1_all.deb
 
 apt-get update
-apt-get install -y libgstreamer-plugins-base1.0-dev:amd64 libgstreamer-plugins-base1.0-dev:i386 \
-                    libasound2-plugins:amd64 libasound2-plugins:i386 \
-                    libmjpegutils-2.1-0:amd64 libmjpegutils-2.1-0:i386 \
-                    gstreamer1.0-libav:amd64 gstreamer1.0-libav:i386 \
-                    gstreamer1.0-plugins-base:amd64 gstreamer1.0-plugins-good:amd64 \
-                    gstreamer1.0-plugins-bad:amd64 gstreamer1.0-plugins-ugly:amd64 \
-                    gstreamer1.0-plugins-base:i386 gstreamer1.0-plugins-good:i386 \
-                    gstreamer1.0-plugins-bad:i386 gstreamer1.0-plugins-ugly:i386 \
-                    || echo "FATAL ERROR"
+install_libs \
+                libgstreamer-plugins-base1.0-dev:amd64 libgstreamer-plugins-base1.0-dev:i386 \
+                libasound2-plugins:amd64 libasound2-plugins:i386 \
+                libmjpegutils-2.1-0:amd64 libmjpegutils-2.1-0:i386 \
+                gstreamer1.0-libav:amd64 gstreamer1.0-libav:i386 \
+                gstreamer1.0-plugins-base:amd64 gstreamer1.0-plugins-good:amd64 \
+                gstreamer1.0-plugins-bad:amd64 gstreamer1.0-plugins-ugly:amd64 \
+                gstreamer1.0-plugins-base:i386 gstreamer1.0-plugins-good:i386 \
+                gstreamer1.0-plugins-bad:i386 gstreamer1.0-plugins-ugly:i386
+
+# FFMPEG devel dependencies
+install_libs \
+                libavcodec-dev libavcodec-dev:i386 \
+                libavformat-dev libavformat-dev:i386 \
+                libavutil-dev libavutil-dev:i386 \
+                libavfilter-dev libavfilter-dev:i386 \
+                libavdevice-dev libavdevice-dev:i386 \
+                libswscale-dev libswscale-dev:i386 \
+                libswresample-dev libswresample-dev:i386 \
+                libx264-dev libx264-dev:i386 \
+                libx265-dev libx265-dev:i386 \
+                libvpx-dev libvpx-dev:i386 \
+                libopus-dev libopus-dev:i386
 
 # Misc utilities (not sure if fontconfig is required)
-apt-get -y install wget build-essential vim nano fontconfig flex dh-autoreconf meson cmake \
-|| echo "FATAL ERROR"
+install_libs wget build-essential vim nano fontconfig flex dh-autoreconf meson cmake
 
 # Runtime dependencies
-apt-get -y install lsb-release || echo "FATAL ERROR"
+install_libs lsb-release
+
+echo "All installed is done"
 
 EOF
 
@@ -188,8 +211,8 @@ create_build_scripts_update () {
 
     sdl2_version="2.26.4"
     faudio_version="23.03"
-    vulkan_headers_version="1.3.239"
-    vulkan_loader_version="1.3.239"
+    vulkan_headers_version="1.4.304"
+    vulkan_loader_version="1.4.304"
     spirv_headers_version="sdk-1.3.239.0"
     libpcap_version="1.10.4"
     libxkbcommon_version="1.6.0"
@@ -215,8 +238,10 @@ wget -O vulkan-headers.tar.gz https://github.com/KhronosGroup/Vulkan-Headers/arc
 wget -O spirv-headers.tar.gz https://github.com/KhronosGroup/SPIRV-Headers/archive/${spirv_headers_version}.tar.gz
 wget -O libpcap.tar.gz https://www.tcpdump.org/release/libpcap-${libpcap_version}.tar.gz
 wget -O libxkbcommon.tar.xz https://xkbcommon.org/download/libxkbcommon-${libxkbcommon_version}.tar.xz
-wget -O /usr/include/linux/ntsync.h https://raw.githubusercontent.com/zen-kernel/zen-kernel/f787614c40519eb2c8ebdc116b2cd09d46e5ec85/include/uapi/linux/ntsync.h
-wget -O /usr/include/linux/userfaultfd.h https://raw.githubusercontent.com/zen-kernel/zen-kernel/f787614c40519eb2c8ebdc116b2cd09d46e5ec85/include/uapi/linux/userfaultfd.h
+
+wget -O /usr/include/linux/ntsync.h https://raw.githubusercontent.com/zen-kernel/zen-kernel/refs/heads/6.13/main/include/uapi/linux/ntsync.h
+wget -O /usr/include/linux/userfaultfd.h https://raw.githubusercontent.com/zen-kernel/zen-kernel/refs/heads/6.13/main/include/uapi/linux/userfaultfd.h
+
 if [ -d /usr/lib/i386-linux-gnu ]; then wget -O wine.deb https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-i386/wine-stable_4.0.3~bionic_i386.deb; fi
 if [ -d /usr/lib/x86_64-linux-gnu ]; then wget -O wine.deb https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-amd64/wine-stable_4.0.3~bionic_amd64.deb; fi
 
@@ -232,25 +257,30 @@ export CFLAGS="-O2"
 export CXXFLAGS="-O2"
 mkdir build && cd build
 
-cmake ../SDL2-${sdl2_version} && make -j$(nproc) && make install
+cmake ../SDL2-${sdl2_version}
+make -j$(nproc) install
 cd ../ && rm -r build && mkdir build && cd build
 
-cmake ../FAudio-${faudio_version} && make -j$(nproc) && make install
+cmake ../FAudio-${faudio_version}
+make -j$(nproc) install
 cd ../ && rm -r build && mkdir build && cd build
 
-cmake ../Vulkan-Headers-${vulkan_headers_version} && make -j$(nproc) && make install
+cmake ../Vulkan-Headers-${vulkan_headers_version}
+make -j$(nproc) install
 cd ../ && rm -r build && mkdir build && cd build
 
 cmake ../Vulkan-Loader-${vulkan_loader_version}
-make -j$(nproc)
-make install
-
+make -j$(nproc) install
 cd ../ && rm -r build && mkdir build && cd build
-cmake ../SPIRV-Headers-${spirv_headers_version} && make -j$(nproc) && make install
+
+cmake ../SPIRV-Headers-${spirv_headers_version}
+make -j$(nproc) install
 cd ../ && dpkg -x wine.deb .
 cp opt/wine-stable/bin/widl /usr/bin
 rm -r build && mkdir build && cd build
-../libpcap-${libpcap_version}/configure && make -j$(nproc) install
+
+../libpcap-${libpcap_version}/configure
+make -j$(nproc) install
 
 cd ../libxkbcommon-${libxkbcommon_version}
 meson setup build -Denable-docs=false
@@ -258,6 +288,8 @@ meson compile -C build
 meson install -C build
 
 cd /opt && rm -r /opt/build_libs
+
+echo "All upgrade is done"
 
 EOF
 
@@ -281,9 +313,9 @@ case "$1" in
         umount "${CHROOT_PATH}"/dev
         ;;
     *)
-        rsync -avz --progress keyring.debian.org::keyrings/keyrings/ /usr/share/keyrings/
-        debootstrap --arch amd64 $CHROOT_DISTRO "${CHROOT_X64}" $CHROOT_MIRROR
-        [[ "$?" != 0 ]] && echo "error: create 64_chroot"
+#         rsync -avz --progress keyring.debian.org::keyrings/keyrings/ /usr/share/keyrings/
+#         debootstrap --arch amd64 $CHROOT_DISTRO "${CHROOT_X64}" $CHROOT_MIRROR
+#         [[ "$?" != 0 ]] && echo "error: create 64_chroot" && exit 1
         create_build_scripts
         prepare_chroot 64
         ;;
