update chroot

diff --git a/01_create_debian_multi b/01_create_debian_multi
--- a/01_create_debian_multi
+++ b/01_create_debian_multi
@@ -88,7 +88,7 @@ apt-get -y install software-properties-common
 dpkg --add-architecture i386
 apt-get update
 
-# Wine dependencies
+echo "Wine dependencies"
 apt-get install -y gcc-10 gcc-multilib g++-10 g++-multilib \
                 g++-mingw-w64-x86-64 g++-mingw-w64-i686 \
                 gcc-mingw-w64-x86-64 gcc-mingw-w64-i686 \
@@ -133,14 +133,24 @@ apt-get install -y gcc-10 gcc-multilib g++-10 g++-multilib \
                 x11proto-dev \
                 libdrm-dev libdrm-dev:i386 \
                 libxkbcommon-dev libxkbcommon-dev:i386 \
-                libxcb1-dev libxcb1-dev:i386 \
-                || echo "FATAL ERROR" && exit 1
+                || echo "FATAL ERROR"
 
-# More wine dependencies
+apt-get install -y \
+                libxcb-xkb-dev libxcb-xkb-dev:i386 \
+                libxcb-xkb1 libxcb-xkb1:i386 \
+                libxcb1-dev libxcb1-dev:i386 \
+                libxml++2.6-dev libxml++2.6-dev:i386 \
+                bash-completion wayland-protocols \
+                valgrind || echo "FATAL ERROR"
+
+                sleep 5
+
+echo "More wine dependencies"
+sleep 1
 apt-get install -y ccache netbase curl ca-certificates \
 				xserver-xorg-video-dummy xserver-xorg xfonts-base xinit fvwm \
 				winbind fonts-liberation2 fonts-noto-core fonts-noto-cjk pulseaudio \
-                || echo "FATAL ERROR" && exit 1
+                python-setuptools openssl || echo "FATAL ERROR"
 
 # Gstreamer codecs
 
@@ -158,18 +168,14 @@ apt-get install -y libgstreamer-plugins-base1.0-dev:amd64 libgstreamer-plugins-b
                     gstreamer1.0-plugins-bad:amd64 gstreamer1.0-plugins-ugly:amd64 \
                     gstreamer1.0-plugins-base:i386 gstreamer1.0-plugins-good:i386 \
                     gstreamer1.0-plugins-bad:i386 gstreamer1.0-plugins-ugly:i386 \
-                    || echo "FATAL ERROR" && exit 1
+                    || echo "FATAL ERROR"
 
 # Misc utilities (not sure if fontconfig is required)
-apt-get -y install wget build-essential vim nano fontconfig flex dh-autoreconf \
-|| echo "FATAL ERROR" && exit 1
+apt-get -y install wget build-essential vim nano fontconfig flex dh-autoreconf meson cmake \
+|| echo "FATAL ERROR"
 
 # Runtime dependencies
-apt-get -y install lsb-release || echo "FATAL ERROR" && exit 1
-apt-get clean
-
-# NTSYNC
-wget -O /usr/include/linux/ntsync.h https://raw.githubusercontent.com/zen-kernel/zen-kernel/f787614c40519eb2c8ebdc116b2cd09d46e5ec85/include/uapi/linux/ntsync.h
+apt-get -y install lsb-release || echo "FATAL ERROR"
 
 EOF
 
@@ -180,35 +186,108 @@ EOF
 
 create_build_scripts_update () {
 
+    sdl2_version="2.26.4"
+    faudio_version="23.03"
+    vulkan_headers_version="1.3.239"
+    vulkan_loader_version="1.3.239"
+    spirv_headers_version="sdk-1.3.239.0"
+    libpcap_version="1.10.4"
+    libxkbcommon_version="1.6.0"
+
 	cat <<EOF > "${MAINDIR_CHROOTS}"/prepare_chroot.sh
 #!/bin/bash
 
 apt-get update
 apt-get -y upgrade
 apt-get -y dist-upgrade
-apt-get autoremove -y
-apt-get clean -y
 
-# NTSYNC
+export PATH="/usr/local/bin:\${PATH}"
+if [[ -d /opt/build_libs ]] ; then
+    rm -f /opt/build_libs
+fi
+mkdir /opt/build_libs
+cd /opt/build_libs
+
+wget -O sdl.tar.gz https://www.libsdl.org/release/SDL2-${sdl2_version}.tar.gz
+wget -O faudio.tar.gz https://github.com/FNA-XNA/FAudio/archive/${faudio_version}.tar.gz
+wget -O vulkan-loader.tar.gz https://github.com/KhronosGroup/Vulkan-Loader/archive/v${vulkan_loader_version}.tar.gz
+wget -O vulkan-headers.tar.gz https://github.com/KhronosGroup/Vulkan-Headers/archive/v${vulkan_headers_version}.tar.gz
+wget -O spirv-headers.tar.gz https://github.com/KhronosGroup/SPIRV-Headers/archive/${spirv_headers_version}.tar.gz
+wget -O libpcap.tar.gz https://www.tcpdump.org/release/libpcap-${libpcap_version}.tar.gz
+wget -O libxkbcommon.tar.xz https://xkbcommon.org/download/libxkbcommon-${libxkbcommon_version}.tar.xz
 wget -O /usr/include/linux/ntsync.h https://raw.githubusercontent.com/zen-kernel/zen-kernel/f787614c40519eb2c8ebdc116b2cd09d46e5ec85/include/uapi/linux/ntsync.h
+wget -O /usr/include/linux/userfaultfd.h https://raw.githubusercontent.com/zen-kernel/zen-kernel/f787614c40519eb2c8ebdc116b2cd09d46e5ec85/include/uapi/linux/userfaultfd.h
+if [ -d /usr/lib/i386-linux-gnu ]; then wget -O wine.deb https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-i386/wine-stable_4.0.3~bionic_i386.deb; fi
+if [ -d /usr/lib/x86_64-linux-gnu ]; then wget -O wine.deb https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-amd64/wine-stable_4.0.3~bionic_amd64.deb; fi
+
+tar xf sdl.tar.gz
+tar xf faudio.tar.gz
+tar xf vulkan-loader.tar.gz
+tar xf vulkan-headers.tar.gz
+tar xf spirv-headers.tar.gz
+tar xf libpcap.tar.gz
+tar xf libxkbcommon.tar.xz
+
+export CFLAGS="-O2"
+export CXXFLAGS="-O2"
+mkdir build && cd build
+
+cmake ../SDL2-${sdl2_version} && make -j$(nproc) && make install
+cd ../ && rm -r build && mkdir build && cd build
+
+cmake ../FAudio-${faudio_version} && make -j$(nproc) && make install
+cd ../ && rm -r build && mkdir build && cd build
+
+cmake ../Vulkan-Headers-${vulkan_headers_version} && make -j$(nproc) && make install
+cd ../ && rm -r build && mkdir build && cd build
+
+cmake ../Vulkan-Loader-${vulkan_loader_version}
+make -j$(nproc)
+make install
+
+cd ../ && rm -r build && mkdir build && cd build
+cmake ../SPIRV-Headers-${spirv_headers_version} && make -j$(nproc) && make install
+cd ../ && dpkg -x wine.deb .
+cp opt/wine-stable/bin/widl /usr/bin
+rm -r build && mkdir build && cd build
+../libpcap-${libpcap_version}/configure && make -j$(nproc) install
+
+cd ../libxkbcommon-${libxkbcommon_version}
+meson setup build -Denable-docs=false
+meson compile -C build
+meson install -C build
+
+cd /opt && rm -r /opt/build_libs
 
 EOF
 
-	chmod +x "${MAINDIR_CHROOTS}"/prepare_chroot.sh
-	echo "MAINDIR_CHROOTS=${MAINDIR_CHROOTS}"
-	mv "${MAINDIR_CHROOTS}"/prepare_chroot.sh "${CHROOT_X64}"/opt
+    chmod +x "${MAINDIR_CHROOTS}"/prepare_chroot.sh
+    echo "MAINDIR_CHROOTS=${MAINDIR_CHROOTS}"
+    mv "${MAINDIR_CHROOTS}"/prepare_chroot.sh "${CHROOT_X64}"/opt
 }
 
-if [[ "$1" == "update" ]] ; then
-    create_build_scripts_update
-    prepare_chroot 64
-else
-    rsync -avz --progress keyring.debian.org::keyrings/keyrings/ /usr/share/keyrings/
-    debootstrap --arch amd64 $CHROOT_DISTRO "${CHROOT_X64}" $CHROOT_MIRROR
-    [[ "$?" != 0 ]] && echo "error: create 64_chroot" && exit 1
-    create_build_scripts
-    prepare_chroot 64
-fi
+case "$1" in
+    update)
+        create_build_scripts_update
+        prepare_chroot 64
+        ;;
+    unmount)
+        echo "Unmount chroot directories"
+        umount -l "${CHROOT_PATH}"
+        umount "${CHROOT_PATH}"/proc
+        umount "${CHROOT_PATH}"/sys
+        umount "${CHROOT_PATH}"/dev/pts
+        umount "${CHROOT_PATH}"/dev/shm
+        umount "${CHROOT_PATH}"/dev
+        ;;
+    *)
+        rsync -avz --progress keyring.debian.org::keyrings/keyrings/ /usr/share/keyrings/
+        debootstrap --arch amd64 $CHROOT_DISTRO "${CHROOT_X64}" $CHROOT_MIRROR
+        [[ "$?" != 0 ]] && echo "error: create 64_chroot"
+        create_build_scripts
+        prepare_chroot 64
+        ;;
+esac
 
 rm "${CHROOT_X64}"/opt/prepare_chroot.sh
 
