updated ntsync and added libglvnd

diff --git a/01_create_debian_multi b/01_create_debian_multi
--- a/01_create_debian_multi
+++ b/01_create_debian_multi
@@ -216,6 +216,7 @@ create_build_scripts_update () {
     spirv_headers_version="sdk-1.3.239.0"
     libpcap_version="1.10.4"
     libxkbcommon_version="1.6.0"
+    libglvnd_version="1.7.0"
 
 	cat <<EOF > "${MAINDIR_CHROOTS}"/prepare_chroot.sh
 #!/bin/bash
@@ -239,6 +240,8 @@ wget -O spirv-headers.tar.gz https://github.com/KhronosGroup/SPIRV-Headers/archi
 wget -O libpcap.tar.gz https://www.tcpdump.org/release/libpcap-${libpcap_version}.tar.gz
 wget -O libxkbcommon.tar.xz https://xkbcommon.org/download/libxkbcommon-${libxkbcommon_version}.tar.xz
 
+wget -O libglvnd.tar.gz https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v${libglvnd_version}/libglvnd-v${libglvnd_version}.tar.gz
+
 wget -O /usr/include/linux/ntsync.h https://raw.githubusercontent.com/zen-kernel/zen-kernel/refs/heads/6.13/main/include/uapi/linux/ntsync.h
 wget -O /usr/include/linux/userfaultfd.h https://raw.githubusercontent.com/zen-kernel/zen-kernel/refs/heads/6.13/main/include/uapi/linux/userfaultfd.h
 
@@ -252,6 +255,7 @@ tar xf vulkan-headers.tar.gz
 tar xf spirv-headers.tar.gz
 tar xf libpcap.tar.gz
 tar xf libxkbcommon.tar.xz
+tar xf libglvnd.tar.gz
 
 export CFLAGS="-O2"
 export CXXFLAGS="-O2"
@@ -287,6 +291,11 @@ meson setup build -Denable-docs=false
 meson compile -C build
 meson install -C build
 
+cd ../libglvnd-v${libglvnd_version}
+meson setup build
+meson compile -C build
+meson install -C build
+
 cd /opt && rm -r /opt/build_libs
 
 echo "All upgrade is done"
@@ -313,9 +322,9 @@ case "$1" in
         umount "${CHROOT_PATH}"/dev
         ;;
     *)
-#         rsync -avz --progress keyring.debian.org::keyrings/keyrings/ /usr/share/keyrings/
-#         debootstrap --arch amd64 $CHROOT_DISTRO "${CHROOT_X64}" $CHROOT_MIRROR
-#         [[ "$?" != 0 ]] && echo "error: create 64_chroot" && exit 1
+        rsync -avz --progress keyring.debian.org::keyrings/keyrings/ /usr/share/keyrings/
+        debootstrap --arch amd64 $CHROOT_DISTRO "${CHROOT_X64}" $CHROOT_MIRROR
+        [[ "$?" != 0 ]] && echo "error: create 64_chroot" && exit 1
         create_build_scripts
         prepare_chroot 64
         ;;
